excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://miarora2112.github.io
title: miarora2112
tagline: Words are living thing .. I believe !! 
description: My awesome new site
paginate: 5